Support localized HTML strings in Lombiq.VueJs
Lombiq/Orchard-Vue.js pull request #133
Opened 2024-04-27 17:03 UTC by sarahelsaig

2024-04-29 15:15 UTC, wAsnk requested changes

2024-04-29 15:15 UTC, wAsnk commented on Lombiq.VueJs/Services/VueSingleFileComponentShapeTemplateViewEngine.cs
> +                    "[[{{converter}} input ]]. Please include the inner spacing to ensure future compatibility. Your " +
```suggestion
                    "Vue SFC localization strings should follow the following formats: [[ text ]], [[{ html }]] or " +
                    "[[{converter} input ]]. Please include the inner spacing to ensure future compatibility. Your " +
```
Isn't this the correct syntax?

2024-04-29 17:37 UTC, sarahelsaig commented on Lombiq.VueJs/Services/VueSingleFileComponentShapeTemplateViewEngine.cs
> +                    "[[{{converter}} input ]]. Please include the inner spacing to ensure future compatibility. Your " +
`{{` is an escape sequence, `[[{converter} input ]]` would tell the logger to look for an optional argument named "converter" See the `\"{Expression}\"` on line 111.

If you let this execute, the log will be like:
```
2024-04-29 18:48:35.6921|Default|00-e95b88e0bb813a610f82e14827b7410c-ea9a812249d69f0a-00||Lombiq.VueJs.Services.VueSingleFileComponentShapeTemplateViewEngine|WARN|Vue SFC localization strings should follow the following formats: [[ text ]], [[{ html }]] or [[{converter} input ]]. Please include the inner spacing to ensure future compatibility. Your expression was: "[[Test free of charge ]]". 
```

2024-04-30 10:30 UTC, wAsnk approved these changes

2024-04-30 10:30 UTC, merged