OSOE-158: Typo fixes
Lombiq/Orchard-Vue.js pull request #60
Opened 2022-10-19 09:12 UTC by Luko6

OSOE-158

2022-10-20 14:18 UTC, Piedone requested changes

2022-10-20 14:18 UTC, Piedone commented on Lombiq.VueJs.Samples/Views/VueSfc/Index.cshtml
> +   the script which was tanspiled using Rollup and Buble among others.
Bublé is the name.

2022-10-20 14:18 UTC, Piedone commented on Lombiq.VueJs/Assets/Scripts/helpers/get-vue-files.js
> -const asDirent = { withFileTypes: true };
This looks more like an abbreviation for "as directory entry". Check if indeed, and use a non-abbreviated name then. Same for `dirent` below.

2022-10-21 14:56 UTC, Piedone requested changes

2022-10-21 14:56 UTC, Piedone commented on Lombiq.VueJs/Assets/Scripts/helpers/get-vue-files.js
> +    getVueComponents: readDirectoryFunction((dirent) => dirent.name.endsWith('.vue') && dirent.isFile()),
As I've written under https://github.com/Lombiq/Orchard-Vue.js/pull/60#discussion_r1000697996:

>  Check if indeed, and use **a non-abbreviated name then**.

2022-10-24 11:06 UTC, Luko6 commented on Lombiq.VueJs/Assets/Scripts/helpers/get-vue-files.js
> +    getVueComponents: readDirectoryFunction((dirent) => dirent.name.endsWith('.vue') && dirent.isFile()),
[Dirent](https://nodejs.org/api/fs.html#class-fsdirent) is a name used by the library though, so I think it's most logical that this stays as is.

2022-10-24 11:53 UTC, Piedone commented on Lombiq.VueJs/Assets/Scripts/helpers/get-vue-files.js
> +    getVueComponents: readDirectoryFunction((dirent) => dirent.name.endsWith('.vue') && dirent.isFile()),
I see, OK then.

2022-10-24 13:40 UTC, Piedone approved these changes

2022-10-24 22:05 UTC, merged